main/urls.py
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from django.urls import re_path

from www import views
from main import settings

urlpatterns = [
    path('admin/',                  admin.site.urls,                name='admin'),
    path('',                        views.index,                    name='index'),
    path('company/about/',          views.company_about,            name='company_about'),
    path('company/vision/',         views.company_vision,           name='company_vision'),
    path('company/history/',        views.company_history,          name='company_history'),
    path('company/orgnation/',      views.company_orgnation,        name='company_orgnation'),
    path('company/certificate/',    views.company_certificate,      name='company_certificate'),
    path('company/map/',            views.company_map,              name='company_map'),
    path('product/dispenser/',      views.product_dispenser,        name='product_dispenser'),
    path('product/diebonder/',      views.product_diebonder,        name='product_diebonder'),
    path('product/attach/',         views.product_attach,           name='product_attach'),
    path('investment/disclosure/',  views.investment_disclosure,    name='investment_disclosure'),
    path('investment/stock/',       views.investment_stock,         name='investment_stock'),
    path('investment/finance/',     views.investment_finance,       name='investment_finance'),
    path('investment/notice/',      views.investment_notice,        name='investment_notice'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

admin.site.site_header = "관리자페이지" #"Django Administration"
admin.site.index_title = "Site administration"
admin.site.site_title = "Django site admin"

www/models.py
from django.db import models

class Notice(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField()

class NoticeAttach(models.Model):
    notice = models.ForeignKey(Notice, on_delete=models.CASCADE, null=True)
    file = models.FileField(null=True, blank=True, upload_to="")

www/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup
import requests
import datetime
import json
from .models import Notice

def index(request):
    url = 'https://finance.naver.com/item/main.nhn?code=053610'
    response = requests.get(url)
    response.raise_for_status()
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    _nowVal = soup.select_one('#content > div.section.trade_compare > table > tbody > tr:nth-child(1) > td:nth-child(2)')
    _nowVal = _nowVal.text
    #print(_nowVal)
    url = 'https://finance.naver.com/sise'
    response = requests.get(url)
    response.raise_for_status()
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    _kospi = soup.select_one('#KOSPI_now')
    _kospi = _kospi.text
    #print(_kospi)
    _kosdaq = soup.select_one('#KOSDAQ_now')
    _kosdaq = _kosdaq.text
    #print(_kosdaq)
    stock = {'nowVal': _nowVal, 'kosdaq': _kosdaq, 'kospi': _kospi}
    return render(request, 'www/index.html', {'stock': stock})
def company_about(request):
    return render(request, 'www/company_about.html', {'message': 'company'})
def company_vision(request):
    return render(request, 'www/company_vision.html', {'message': 'vision'})
def company_history(request):
    return render(request, 'www/company_history.html', {'message': 'history'})
def company_orgnation(request):
    return render(request, 'www/company_orgnation.html', {'message': 'orgnation'})
def company_certificate(request):
    return render(request, 'www/company_certificate.html', {'message': 'certificate'})
def company_map(request):
    return render(request, 'www/company_map.html', {'message': 'map'})
def product_dispenser(request):
    return render(request, 'www/product_dispenser.html', {'message': 'dispenser'})
def product_diebonder(request):
    return render(request, 'www/product_diebonder.html', {'message': 'diebonder'})
def product_attach(request):
    return render(request, 'www/product_attach.html', {'message': 'attach'})
def investment_disclosure(request):
    with open("secret.json") as f:
        secrets = json.loads(f.read())
    DART_KEY = secrets['DART_KEY']
    date_ago = datetime.datetime.now() - datetime.timedelta(days=365)
    print(date_ago.strftime("%Y%m%d"))
    startDate = date_ago.strftime("%Y%m%d")
    url = 'https://opendart.fss.or.kr/api/list.json?crtfc_key='+DART_KEY+'&corp_code=00325112&bgn_de='+startDate
    response = requests.get(url)
    response.raise_for_status()
    return render(request, 'www/investment_disclosure.html', {'message': response.json()['list']})



"""
def investment_stock(request):
    url = 'https://finance.naver.com/item/sise.nhn?code=053610'
    response = requests.get(url)
    response.raise_for_status()
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    _현재가 = soup.select_one('#_nowVal').text
    _전일대비 = soup.select_one('#_diff').text
    _전일대비 = _전일대비.replace("상승", "▲")
    _전일대비 = _전일대비.replace("하락", "▼")
    _등락률 = soup.select_one('#_rate').text
    _시가 = soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(4) > td:nth-child(4) > span:nth-child(1)').text
    _고가52 = soup.select_one('#_high').text
    _저가52 = soup.select_one('#_low').text
    _거래량 = soup.select_one('#_quant').text
    _전일가 = soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(3) > td:nth-child(4) > span:nth-child(1)').text
    _최고 = soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(11) > td:nth-child(2) > span:nth-child(1)').text
    _최저 = soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(11) > td:nth-child(4) > span:nth-child(1)').text
    _상한가    =   soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(8) > td:nth-child(2) > span:nth-child(1)').text
    _하한가    =   soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(9) > td:nth-child(2) > span:nth-child(1)').text
    _PER = soup.select_one('#_sise_per').text
    _액면가    =   soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(6) > td:nth-child(2) > span:nth-child(1)').text
    _상장주식수  =   soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(12) > td:nth-child(4) > span:nth-child(1) > span:nth-child(1)').text
    _시가총액   =   soup.select_one('.type_tax > tbody:nth-child(2) > tr:nth-child(12) > td:nth-child(2) > span:nth-child(1)').text
    url = 'http://asp1.krx.co.kr/servlet/krx.asp.XMLSise?code=053610'
    response = requests.get(url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    dailystocks = {}
    for dailystock in soup.findAll('dailystock'):
        day = {}
        day['day_date'] = 'day_date'
        day['day_dungrak'] = 'day_dungrak'
        day['day_endprice'] = 'day_endprice'
        day['day_getamount'] = 'day_getamount'
        day['day_getdebi'] = 'day_getdebi'
        day['day_high'] = 'day_high'
        day['day_low'] = 'day_low'
        day['day_start'] = 'day_start'
        day['day_volume'] = 'day_volume'
        dailystocks[dailystock['day_date']] = day

    url = 'https://finance.naver.com/item/main.nhn?code=053610'
    response = requests.get(url)
    response.raise_for_status()
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')
    매도1 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(2) > td:nth-child(1)').text
    매도2 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(3) > td:nth-child(1)').text
    매도3 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(4) > td:nth-child(1)').text
    매도4 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(5) > td:nth-child(1)').text
    매도5 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(6) > td:nth-child(1)').text
    매수1 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(2) > td:nth-child(3)').text
    매수2 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(3) > td:nth-child(3)').text
    매수3 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(4) > td:nth-child(3)').text
    매수4 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(5) > td:nth-child(3)').text
    매수5 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(6) > td:nth-child(3)').text
    매도1거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(2) > td:nth-child(2) > em:nth-child(1)').text
    매도2거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(3) > td:nth-child(2) > em:nth-child(1)').text
    매도3거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(4) > td:nth-child(2) > em:nth-child(1)').text
    매도4거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(5) > td:nth-child(2) > em:nth-child(1)').text
    매도5거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(6) > td:nth-child(2) > em:nth-child(1)').text
    매수1거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(2) > td:nth-child(4) > em:nth-child(1)').text
    매수2거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(3) > td:nth-child(4) > em:nth-child(1)').text
    매수3거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(4) > td:nth-child(4) > em:nth-child(1)').text
    매수4거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(5) > td:nth-child(4) > em:nth-child(1)').text
    매수5거래량 = soup.select_one('div.section:nth-child(9) > div:nth-child(2) > table:nth-child(2) > tbody:nth-child(5) > tr:nth-child(6) > td:nth-child(4) > em:nth-child(1)').text
    stock = {
        '현재가': _현재가, '전일대비': _전일대비, '등락률': _등락률, '시가': _시가, '고가52': _고가52, '저가52': _저가52, '거래량': _거래량,
        '전일가': _전일가, "최고": _최고, "최저": _최저, '상한가': _상한가, '하한가': _하한가, 'PER': _PER, '액면가': _액면가, '상장주식수': _상장주식수, '시가총액': _시가총액,
    }
    frgn = {
        '매도1': 매도1, '매도2': 매도2, '매도3': 매도3, '매도4': 매도4, '매도5': 매도5,
        '매수1': 매수1, '매수2': 매수2, '매수3': 매수3, '매수4': 매수4, '매수5': 매수5,
        '매도1거래량': 매도1거래량, '매도2거래량': 매도2거래량, '매도3거래량': 매도3거래량, '매도4거래량': 매도4거래량, '매도5거래량': 매도5거래량,
        '매수1거래량': 매수1거래량, '매수2거래량': 매수2거래량, '매수3거래량': 매수3거래량, '매수4거래량': 매수4거래량, '매수5거래량': 매수5거래량
    }
    return render(request, 'www/investment_stock.html', {'stock': stock, 'frgn': frgn, 'dailystocks': dailystocks})
"""




def investment_stock(request):
    return render(request, 'www/investment_stock.html', {'stock': 'stock', 'frgn': 'frgn', 'dailystocks': 'dailystocks'})
def investment_finance(request):
    return render(request, 'www/investment_finance.html', {'finance': 'finance'})
def investment_notice(request):
    notices = Notice.objects.all().order_by('-date')
    return render(request, 'www/investment_notice.html', {'notices': notices})

templates/www/certificate.html
{% load static %}
<html lang="ko">
<head>
{% include "www/share/head.html" %}
</head>
<body>
<div class="container" style="background-image: url('{% static 'www\main02.png' %}')">
    <br>
    {% include "www/share/navbar.html" %}
    <div style="height:221px"></div>
<!-- 사이드메뉴 -->
<div class="row" style="background-color: #efefef;">
    <div class="col-xs p-4" style="width: 250px; border-right: 1px solid lightgray">
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="#">회사소개</a>
                <div class="font-sans-300" style="font-size: 20px">
                    <li><a style="color: dimgray" href="../company">- 회사개요</a></li>
                    <li><a style="color: dimgray" href="../vision">- 기업비전</a></li>
                    <li><a style="color: dimgray" href="../history">- 회사연혁</a></li>
                    <li><a style="color: dimgray" href="../orgnation">- 조직도</a></li>
                    <li><a style="color: dimgray" href="../certificate">- 지적재산권</a></li>
                    <li><a style="color: dimgray" href="../map">- 오시는길</a></li>
                </div>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="../product">제품소개</a>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="../notice" >공지사항</a>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="#" onclick="javascript:alert('준비중입니다.')">투자정보</a>
            </ul>
        </div>
    </div>
    <div class="m-2 font-sans-400" style="width: 1000px;">
        <div style="text-align: right; font-size: 12px;">홈 > 회사소개 > 지적재산권</div>
        <div class="col-xs" style="font-size: 25px">지적재산권</div>
        <div class="col-xs" style="border-bottom: 1px solid lightgray"><br>
<pre class="font-serif-500" style="font-size: 26px">
세계속에 당당한 프로텍
프로텍은 최고의 인재와 기술력을 바탕으로 최고의 가치를 창출합니다.
</pre>
        </div><br>
        <div class="row" style="width: 1000px">
            <div class="m-5 p-4" style="width: 250px">
                <p style="font-size: 20px">특허</p>
                - 국내특허 : 67개<br>
                - 해외특허 : 12개<br>
                - 실용신안 : 23개<br>
            </div>
            <div class="p-5" style="border-bottom: 1px solid lightgray">
                <img width="150" height="180" src="{% static 'www/img/certificate01.png' %}">　
                <img width="150" height="180" src="{% static 'www/img/certificate01.png' %}">　
                <img width="150" height="180" src="{% static 'www/img/certificate01.png' %}">
            </div>
        </div>
        <div class="row" style="width: 1000px">
            <div class="m-5 p-4" style="width: 250px;">
                <p style="font-size: 20px">인증</p>
                - ISO9000<br>
                - ISO14000<br>
                - CE / UL<br>
                - 신기술벤처기업<br>
            </div>
            <div class="p-5">
                <img width="150" height="180" src="{% static 'www/img/certificate02.png' %}">　
                <img width="150" height="180" src="{% static 'www/img/certificate02.png' %}">　
                <img width="150" height="180" src="{% static 'www/img/certificate02.png' %}">
            </div>
        </div>
    </div>
</div>
{% include "www/share/footer.html" %}
</div>
{% include "www/share/script.html" %}
</body>
</html>

templates/www/company.html
{% load static %}
<html lang="ko">
<head>
{% include "www/share/head.html" %}
</head>
<body>
<div class="container" style="background-image: url('{% static 'www\main02.png' %}')">
    <br>
    {% include "www/share/navbar.html" %}
    <div style="height:221px"></div>
<!-- 사이드메뉴 -->
<div class="row" style="background-color: #efefef;">
    <div class="col-xs p-4" style="width: 250px; border-right: 1px solid lightgray">
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="#">회사소개</a>
                <div class="font-sans-300" style="font-size: 20px">
                    <li><a style="color: dimgray" href="../company">- 회사개요</a></li>
                    <li><a style="color: dimgray" href="../vision">- 기업비전</a></li>
                    <li><a style="color: dimgray" href="../history">- 회사연혁</a></li>
                    <li><a style="color: dimgray" href="../orgnation">- 조직도</a></li>
                    <li><a style="color: dimgray" href="../certificate">- 지적재산권</a></li>
                    <li><a style="color: dimgray" href="../map">- 오시는길</a></li>
                </div>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="../product">제품소개</a>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="../notice" >공지사항</a>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="#" onclick="javascript:alert('준비중입니다.')">투자정보</a>
            </ul>
        </div>
    </div>
    <div class="m-2 font-sans-400" style="width: 1000px;">
        <div style="text-align: right; font-size: 12px;">홈 > 회사소개 > 회사개요</div>
        <div class="col-xs" style="font-size: 25px">회사개요</div>
        <div class="col-xs" style="border-bottom: 1px solid lightgray"><br>
<pre class="font-serif-500" style="font-size: 26px">
세계속에 당당한 프로텍
프로텍은 최고의 인재와 기술력을 바탕으로 최고의 가치를 창출합니다.
</pre>
        </div>
        <div class="row">
            <div class="p-5">
<pre class="font-sans-300" style="font-size: 17px">
프로텍은 1997년 설립된 반도체 패키징관련 장비 제조 업체입니다.
프로텍은 설립 이후 끊임없는 연구와 개발에 힘써 현재 반도체 및
LED, SMTA분야의 고정도의 디스펜싱 분야 및 패키징 분야에서
세계적인 기업으로 성장하였습니다.
프로텍은 반도체 디펜싱 분야에서 세계를 제패한 기술력과 자신감을
바탕으로 반도체 및 LED 패키징 분야의 토탈 솔루션을 제공할 수
있도록 끊임없는 연구와 개발을 하고 있으며 이를 통해
국가 산업발전에 기여하고 세계 최고의 반도체 장비 제조 기업이
되도록 최선을 다할 것입니다.
고객 여려분의 애정과 성원이 있기에 프로텍은 오늘도 도전을
현실로 만들어 가고 있습니다.

감사합니다.

대표이사 최승환
</pre>
            </div>
            <div class="p-5">
                <img class="img-thumbnail" src="{% static 'www/img/ceo.png' %}" width="260px" style="filter: grayscale(50%)">
            </div>
        </div>


        <div class="row p-5">
            <div style="width: 900px">
            </div>
            <div class="row p-3">
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3315.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3315.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3329.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3329.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3880.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3880.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3889.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3889.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3913.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3913.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/IMG_2314.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/IMG_2314.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/IMG_2379.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/IMG_2379.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/IMG_2344.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/IMG_2344.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/IMG_2351.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/IMG_2351.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3906.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3906.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
                <div class="thumbnail" style="width: 160px; margin: 2px">
                    <a href="{% static 'www/photo/071A3868.JPG' %}">
                        <img class="rounded" src="{% static 'www/photo/071A3868.JPG' %}" style="width:100%">
                        <div class="caption"></div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% include "www/share/footer.html" %}
</div>
{% include "www/share/script.html" %}
</body>
</html>

templates/www/investment_notice.html
{% load static %}
<html lang="ko">
<head>
{% include "www/share/head.html" %}
</head>
<body>
<div class="container" style="background-image: url('{% static 'www/img/finance.jpg' %}')">
    <br>
    {% include "www/share/navbar.html" %}
    <div style="height:221px"></div>
<!-- 사이드메뉴 -->
<div class="row" style="background-color: white">
    <div class="col-xs p-4" style="width: 250px; border-right: 1px solid lightgray">
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="{% url 'company_about' %}">회사소개</a>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black" href="{% url 'product_dispenser' %}">제품정보</a>
            </ul>
        </div>
        <div>
            <ul>
                <a onclick="alert('준비중입니다.')" class="font-sans-500" style="font-size: 26px; color: black" href="#" >고객지원</a>
            </ul>
        </div>
        <div>
            <ul>
                <a class="font-sans-500" style="font-size: 26px; color: black">투자정보</a>
                <div class="font-sans-300" style="font-size: 20px">
                    <li><a style="color: dimgray" href="{% url 'investment_disclosure' %}">- 공시정보</a></li>
                    <li><a style="color: dimgray" href="{% url 'investment_stock' %}">- 주가정보</a></li>
                    <li><a style="color: dimgray" href="{% url 'investment_finance' %}">- 재무정보</a></li>
                    <li><a style="color: dimgray" href="{% url 'investment_notice' %}">- 회사공고</a></li>
                </div>
            </ul>
        </div>
    </div>
    <div class="m-2 font-sans-400" style="width: 1000px;">
        <div style="text-align: right; font-size: 12px;">홈 > 투자정보 > 회사공고</div>
        <div class="col-xs" style="font-size: 25px">회사공고</div>
        <div class="col-xs" style="border-bottom: 1px solid lightgray"><br>
<pre class="font-serif-500" style="font-size: 26px">
프로텍은 고객과 투자자의 이익을 극대화하는 고객중심의 경영을 추구합니다.
</pre>
        </div>
        <div style="height: 50px"></div>
        <div class="font-sans-300" style="margin-left: 40px">
        </div>
        <div class="font-sans-300" style="margin-left: 40px">
        </div>
        <div style="margin-left: 40px"></div>
        <div style="margin-left: 40px">

            <table class="table table-borderless">
                <thead style="background-color: white; color: black; border-top: black solid 2PX; border-bottom: black solid 1px">
                    <tr class="font-sans-500"><td>제목</td><td>공지일자</td></tr>
                </thead>
                <tbody style="background-color: white">
                    {% for notice in notices %}
                    <tr style="border-bottom: gainsboro solid 1px"><td><a data-toggle="modal" href="#notice{{ notice.id }}" style="color: #212121">{{ notice.title }}</a></td><td>{{ notice.date|date:"Y-m-d" }}</td></tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="font-sans-300" style="margin-left: 40px">
        </div>
        <div style="height: 100px"></div>
    </div>
</div>
{% include "www/share/footer.html" %}
</div>
{% include "www/share/script.html" %}



</body>
</html>

{% for notice in notices %}
<div class="modal fade" id="notice{{ notice.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ notice.title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">

<!--                <div class="rounded" style="background-color: whitesmoke; padding: 10px; font-size: 14px">-->

<table class="table table-bordered" style="font-size: 12px; background-color: whitesmoke">
    <tr>
        <th>
            <span style="color: dimgray; margin-right: 5px"><i class="fas fa-paperclip"></i></span>첨부파일
        </th>
    </tr>
    {% for noticeFile in notice.noticeattach_set.all%}
    <tr>
        <td>
            <a href="{{ noticeFile.file.url }}">{{ noticeFile.file }}</a>
        </td>
    </tr>
    {% endfor %}
</table>
<!--                </div>-->

                <div style="padding: 10px">
                    {{ notice.content|linebreaksbr }}
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}